ajuna-network/Ajuna

- Cargo.lock
- runtime/solo/Cargo.toml
> align to polkadot-v0.9.20

- Cargo.lock
- runtime/bajun/Cargo.toml
- runtime/solo/Cargo.toml
> [PLAT-263] Peg dependencies

- .github/workflows/check-pull-request.yml
- Cargo.lock
- node/cli/Cargo.toml
- node/cli/src/command_helper.rs
- node/service/Cargo.toml
- pallets/ajuna-connectfour/Cargo.toml
- pallets/ajuna-gameregistry/src/lib.rs
- pallets/ajuna-gameregistry/src/mock.rs
- pallets/ajuna-gameregistry/src/tests.rs
- runtime/solo/Cargo.toml
- runtime/solo/src/lib.rs
Companion PR for https://github.com/ajuna-network/worker/pull/44.
Changes:
- add `pallet-sidechain`
- peg `pallet-{sidechain,teerex}` at latest master@https://github.com/integritee-network/pallets/commit/4d1b0e9d412b4e3b94f3e5afd853213b6ecc97b7
- align `SignedExtra` type with [integritee-node](https://github.com/integritee-network/integritee-node/blob/ecc97eafd9db460b75df46a99ba8edc01d4180de/runtime/src/lib.rs#L660-L670)
- add a CI job to build and upload dev binary
> [PLAT-265] rebase upstream

- ajuna-common/src/lib.rs
- pallets/ajuna-board/src/guessing.rs
- pallets/ajuna-board/src/lib.rs
- pallets/ajuna-board/src/mock.rs
- pallets/ajuna-board/src/tests.rs
Pull out the guessing game into its own module
Add a board identifier to the struct stored on chain
- [ x] Tests for the changes have been added
> Board pallet refactor

- .github/workflows/check-pull-request.yml
- docker/Dockerfile
Changes:
- remove conditional `SKIP_WASM_BUILD`
- remove caching to build fresh binary
- build dev binary inside `integritee/integritee-dev:0.1.9`
- add missing `--no-default-features`
> Fix build ci

- pallets/ajuna-board/src/lib.rs
- pallets/ajuna-board/src/tests.rs
> clear board state only after finish_game

- .github/workflows/push-to-docker-hub-solochain.yml
> Build docker image when tag pushed.

- Cargo.lock
- ajuna-common/src/lib.rs
- pallets/ajuna-board/Cargo.toml
- pallets/ajuna-board/src/dot4gravity.rs
- pallets/ajuna-board/src/guessing.rs
- pallets/ajuna-board/src/lib.rs
Implementing `TurnBasedGame` for dot4gravity.
> implement TurnBasedGame for dot4gravity

- Cargo.lock
- node/cli/Cargo.toml
- node/cli/src/command_helper.rs
- runtime/solo/src/lib.rs
Reverts ajuna-network/Ajuna#28
> Revert "[PLAT-276] Reinstate CheckNonZeroSender and asset payment for SignedExtra"

- Cargo.lock
- pallets/ajuna-board/Cargo.toml
- pallets/ajuna-board/src/dot4gravity.rs
A companion PR for [polkadot-v0.9.20-dev](https://github.com/ajuna-network/ajuna-games/releases/tag/polkadot-v0.9.20-dev) tag which includes
- https://github.com/ajuna-network/ajuna-games/pull/11
- https://github.com/ajuna-network/ajuna-games/pull/12
- https://github.com/ajuna-network/ajuna-games/pull/13
> update for state returning player instead of index

- .github/workflows/check-pull-request.yml
- .github/workflows/push-to-docker-hub-solochain.yml
Adds Slack notifications for the execution of the `Build` and `Push to Docker Hub` workflows, notifications are sent to the `#github-actions` channel.
> [PLAT-293] Configure Slack notifications for Github Actions

- .github/workflows/end-to-end-tests.yml
- ci/Dockerfile.node
- ci/Dockerfile.worker
- ci/e2e-compose.yml.base
- ci/e2e-tests.sh
This PR aims to add a new step for E2E between the Ajuna node and the worker, additionally it also applies some adjustments to the general steps of other workflows.
> [PLAT-319] End to end testing

- Cargo.lock
- node/cli/Cargo.toml
- node/cli/src/command_helper.rs
- runtime/solo/src/lib.rs
Reinstating the `pallet-asset-tx-payment` as part of [PLAT-276](https://ajunanetwork.atlassian.net/browse/PLAT-276).
> reinstate pallet-asset-tx-payment

- Cargo.lock
- pallets/ajuna-board/src/tests.rs
Bumping `dot4gravity` for [checking game finished](https://github.com/ajuna-network/ajuna-games/pull/18).
> Bump dot4gravity

- .github/workflows/end-to-end-tests.yml
- Cargo.lock
- Cargo.toml
- pallets/ajuna-awesome-avatars/Cargo.toml
- pallets/ajuna-awesome-avatars/README.md
- pallets/ajuna-awesome-avatars/src/benchmarking.rs
- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/mock.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- runtime/solo/Cargo.toml
- runtime/solo/src/lib.rs
> Add AAA skeleton.

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/mock.rs
- pallets/ajuna-awesome-avatars/src/season.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
Implementing seasons as part of [PLAT-391](https://ajunanetwork.atlassian.net/browse/PLAT-391).
> [PLAT-391] AAA Pallet - Seasons

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/season.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
See https://ajunanetwork.atlassian.net/browse/PLAT-389 for details, in short:
* Adds SeasonMetadas storage to track each season's metadata
* Adds extrinsic to update a specific season's metadata
> [PLAT 389] AAA Pallet - Season metadata and logic

- Cargo.lock
- pallets/ajuna-awesome-avatars/Cargo.toml
- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/mock.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- runtime/solo/src/lib.rs
> [PLAT-390] Add config extrinsics.

- ajuna-test/src/sidechain.rs
- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/mock.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
> [PLAT-424] active season

- pallets/ajuna-awesome-avatars/Cargo.toml
- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/mock.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types.rs
> Add single minting structs and methods.

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/mock.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
> [PLAT-443] Ensure mint cooldown.

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types.rs
> [PLAT-404] Add batch minting.

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
See https://ajunanetwork.atlassian.net/browse/PLAT-451 for details. In short:
* Reduced the amount of random numbers generated on the minting process.
> [PLAT-451] Mint optimisation

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/mock.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types.rs
> [AAATAR-199] Add mint count type alias.

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/mock.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types.rs
See https://ajunanetwork.atlassian.net/browse/AAATAR-180 for details. In short:
* Added new fields `rarity_tiers_batch_mint` to be used when minting in batch.
> [AAATAR-180] Batch minting probability increase

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/types.rs
See https://ajunanetwork.atlassian.net/browse/AAATAR-178 for details. In short:
* Added soul points attribute with calculation logic on Avatar generation.
> [AAATAR-178] Mint with soul points

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types.rs
Removing unnecessary extrinsics to prepare for upcoming refactors and benchmarks.
> Consolidate config extrinsics into one

- pallets/battle-mogs/src/lib.rs
- pallets/battle-mogs/src/tests.rs
- pallets/battle-mogs/src/types.rs
See https://ajunanetwork.atlassian.net/browse/BAT-354 for details. In short:
* Hides the value of the compute rarity until the mogwai state goes to Hatched
* Refactors next_gen algoritm for clarity and correctness
> [BAT-354] Rarity only calculated upon hatching

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/mock.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types.rs
[AAATAR-177](https://ajunanetwork.atlassian.net/browse/AAATAR-177)
> [AAATAR-177] Forging

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/mock.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types.rs
[AAATAR-284](https://ajunanetwork.atlassian.net/browse/AAATAR-284)
> [AAATAR-284] Trading

- Cargo.lock
- ajuna-common/Cargo.toml
- ajuna-test/Cargo.toml
- node/Cargo.toml
- node/cli/Cargo.toml
- node/service/Cargo.toml
- pallets/ajuna-awesome-avatars/Cargo.toml
- primitives/Cargo.toml
- rpc/Cargo.toml
- runtime/ajuna/Cargo.toml
- runtime/bajun/Cargo.toml
- runtime/bajun/src/lib.rs
- runtime/solo/Cargo.toml
Updating from `0.1.2` to `0.1.3`
> Release 0.1.3

- runtime/ajuna/src/lib.rs
- runtime/bajun/src/lib.rs
Lowering `MinVestedTransfer` as it's set too high.
> Lower MinVestedTransfer for Bajun and Ajuna

- pallets/battle-mogs/src/tests.rs
See https://ajunanetwork.atlassian.net/browse/BAT-387 for details. In short:
* Added test to verify the removal of a sale entry when the given sold mogwai is bought.
> [BAT-387] Mogwai buy test

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types.rs
Changes:
- add `free_mint_fee_multiplier`
- remove redundant iteration in mint
> Refactor AAA for tests

- pallets/battle-mogs/src/lib.rs
- pallets/battle-mogs/src/tests.rs
- pallets/battle-mogs/src/types.rs
See https://ajunanetwork.atlassian.net/browse/BAT-402 for details. In short:
* Added types for Achivement representation
* Added new storage for achievement tracking
* Added business logic hooks for achievement triggering
> [BAT-402] Achievements

- pallets/battle-mogs/src/algorithm.rs
- pallets/battle-mogs/src/lib.rs
- pallets/battle-mogs/src/types.rs
See https://ajunanetwork.atlassian.net/browse/BAT-353 for details. In short:
* Applied some refactors to the segmenting code.
* Added some tests to verify consistency of segmenting
* Additional linting changes have been applied
> [BAT-353] BattleMogs Pallet | Refactor Genetic Code

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
> [AAATAR-306] forging season based avatars

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/mock.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types.rs
Re: [AAATAR-301](https://ajunanetwork.atlassian.net/browse/AAATAR-301)
> [AAATAR-301] Season treasury

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types.rs
Some refactoring to make AAA more readable.
> Refactor AAA mint

- pallets/ajuna-awesome-avatars/src/benchmarking.rs
- pallets/ajuna-awesome-avatars/src/lib.rs
Adding benchmarks for all the AAA extrinsics.
> [AAATAR-191] Benchmarks

- pallets/battle-mogs/src/lib.rs
- pallets/battle-mogs/src/tests.rs
- pallets/battle-mogs/src/types.rs
See https://ajunanetwork.atlassian.net/browse/BAT-410 for details. In short:
* Merged `MogwaiOwner` storage with `MogwaiStruct` adapted relevant code
> [BAT-410] Merge ownership with mogwai storage

- pallets/battle-mogs/src/lib.rs
- pallets/battle-mogs/src/tests.rs
See https://ajunanetwork.atlassian.net/browse/BAT-356 for details. In short:
* Added specfic Error codes for previously non considered error cases
* Replaced generic errors with specific error codes
> [BAT-356] Fail tests for Errors of the extrinsics

- .github/workflows/release.yml
- docker/Dockerfile
Changes:
- add `ajuna-runtime` for releasing wasm
- fix broken `resources/` path
- add `release-docker` job as part of releasing
> [PLAT-596] Update CI for Ajuna release

- pallets/ajuna-awesome-avatars/src/benchmarking.rs
- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/mock.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types.rs
- runtime/bajun/src/lib.rs
- runtime/solo/src/lib.rs
Re: [AAATAR-318](https://ajunanetwork.atlassian.net/browse/AAATAR-318)
> [AAATAR-318] Extract max_avatar into runtime configurable type

- runtime/ajuna/src/lib.rs
- runtime/ajuna/src/proxy_type.rs
- runtime/bajun/src/lib.rs
- runtime/bajun/src/proxy_type.rs
A followup PR of https://github.com/ajuna-network/Ajuna/pull/148 to sync outdated runtime configuration for Bajun.
> [PLAT-634] Sync up runtime settings

- Cargo.lock
- node/cli/Cargo.toml
- node/service/Cargo.toml
- pallets/ajuna-awesome-avatars/Cargo.toml
- primitives/Cargo.toml
- rpc/Cargo.toml
- runtime/ajuna/Cargo.toml
- runtime/bajun/Cargo.toml
- runtime/solo/Cargo.toml
Upgrade to [paritytech/polkadot@v0.9.32](https://github.com/paritytech/polkadot/releases/tag/v0.9.32).
> [PLAT-642] Upgrade to v0.9.32

- .github/workflows/check-pull-request.yml
> [PLAT-644] Split CI caching

- .github/workflows/check-pull-request.yml
- .github/workflows/release.yml
> Add `srtool` and `subwasm` for CI

- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types/account.rs
> Divide 4 storage tiers evenly

- node/service/src/para.rs
Fixing https://github.com/ajuna-network/Ajuna/actions/runs/3637296942/jobs/6138154833
> Add missing feature guards

- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types/avatar.rs
@darkfriend77: Thanks for catching this 🐛
Changes:
- add a condition to ensure sacrifice avatars are always of equal or higher tier than leader
> Ignore sacrifices of lower tier than leader

- Cargo.lock
- Cargo.toml
- pallets/ajuna-awesome-avatars/Cargo.toml
- pallets/nft-transfer/Cargo.toml
- pallets/nft-transfer/README.md
- pallets/nft-transfer/src/lib.rs
- pallets/nft-transfer/src/mock.rs
- pallets/nft-transfer/src/tests.rs
- pallets/nft-transfer/src/traits.rs
See for details. In short:
* Initial implementation of `nft-transfer` pallet
* Initial testing coverage
* Missing upload business logic, to be done in next phase
> [PLAT-629] Create NFT Transfer Pallet

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/types/config.rs
> Add doc comments for extrinsics and functions.

- .github/workflows/check-pull-request.yml
Reducing the number of jobs to avoid `Error: Process completed with exit code 143`.
> ci: reduce number of jobs for tests

- .github/workflows/check-pull-request.yml
Reducing resources further to avoid 143 error.
> ci: reduce jobs for tests

- pallets/ajuna-awesome-avatars/src/benchmarking.rs
- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types/account.rs
- pallets/ajuna-awesome-avatars/src/types/season.rs
Remove lazy season update logic for `Hooks::on_initialize`.
> [PLAT-687] Implement hooks for season update logic

- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types/season.rs
Adding tests related to mock season 1 settings.
> Add tests for mock season 1

- .github/workflows/check-pull-request.yml
> Run CI against develop

- .github/workflows/check-pull-request.yml
- .github/workflows/cleanup-cache.yml
Changes:
- Run CI on `develop` only
- Clean up cache after PR is closed
> [PLAT-696] Fix CI

- Cargo.lock
- pallets/nft-transfer/Cargo.toml
- pallets/nft-transfer/src/lib.rs
- pallets/nft-transfer/src/mock.rs
- pallets/nft-transfer/src/tests.rs
- pallets/nft-transfer/src/traits.rs
This PR replaces the dependency in `pallet-ajuna-nft-transfer` from `nonfugibles` traits to `nonfungibles_v2`.
Additionaly it replaces the test runtime that used `pallet-uniques` with `pallet-nfts`.
> Update NFT-Transfer pallet

- .github/workflows/check-pull-request.yml
Noticed that CI was passing remotely when clippy was failing locally.
The PR removes discrepancies between remote and local CI settings and updates the cache key to be more specific.
> Fix cache key and CI settings

- Cargo.lock
- pallets/ajuna-awesome-avatars/Cargo.toml
- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/mock.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types/avatar.rs
- pallets/ajuna-nft-transfer/Cargo.toml
- pallets/ajuna-nft-transfer/src/lib.rs
- pallets/ajuna-nft-transfer/src/traits.rs
- runtime/bajun/Cargo.toml
- runtime/bajun/src/lib.rs
- runtime/solo/Cargo.toml
- runtime/solo/src/lib.rs
This PR contains the initial integration of the `pallet-ajuna-nft-transfer` with `pallet-ajuna-awesome-avatars`
> Prototype Integration of NFT-transfer with AAA

- .github/workflows/check-pull-request.yml
- pallets/ajuna-awesome-avatars/src/mock.rs
- pallets/nft-staking/src/mock.rs
This PR changes the testing workflow to only run tests for the pallets in on release branches. On release branches all tests are run as usual.
> [PLAT-740] CI selective tests

- .github/workflows/check-pull-request.yml
> Fix skipped test-full

- .github/workflows/check-pull-request.yml
> Fix expression for branch reference

- .github/workflows/check-pull-request.yml
> Fix outside context reference

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
> fixed most of the comments

- pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/nft.rs
- pallets/ajuna-nft-transfer/src/lib.rs
- pallets/ajuna-nft-transfer/src/tests.rs
- pallets/ajuna-nft-transfer/src/traits.rs
Re: [PLAT-781](https://ajunanetwork.atlassian.net/browse/PLAT-781)
[PLAT-781]: https://ajunanetwork.atlassian.net/browse/PLAT-781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PLAT-781] Handle IPFS URL in NftHandler

- Cargo.lock
- runtime/bajun/Cargo.toml
- runtime/bajun/src/lib.rs
Changes:
- remove unused dependency
- remove call filter on (un)lock_avatar extrinsics
> [PLAT-782] Prepare for v0.1.17 release

- runtime/bajun/src/lib.rs
These values were set to be too low.
> Increase CollectionDeposit & ItemDeposit

- pallets/ajuna-nft-staking/src/contracts.rs
- pallets/ajuna-nft-staking/src/lib.rs
- pallets/ajuna-nft-staking/src/mock.rs
- pallets/ajuna-nft-staking/src/tests.rs
- pallets/ajuna-nft-transfer/src/lib.rs
- runtime/solo/src/lib.rs
Adding `fee_clauses` with tidy ups.
> [PLAT-779] Add fee clause

- pallets/ajuna-nft-staking/src/contracts.rs
- pallets/ajuna-nft-staking/src/lib.rs
- pallets/ajuna-nft-staking/src/tests/ext/accept.rs
- pallets/ajuna-nft-staking/src/tests/ext/cancel.rs
- pallets/ajuna-nft-staking/src/tests/ext/claim.rs
- pallets/ajuna-nft-staking/src/tests/ext/snipe.rs
- pallets/ajuna-nft-staking/src/tests/mock.rs
- runtime/solo/src/lib.rs
To snipe someone's expired contract, one must have contracts being staked.
> [PLAT-788] Sniper condition

- pallets/ajuna-nft-staking/benchmarking/src/lib.rs
- pallets/ajuna-nft-staking/benchmarking/src/mock.rs
- pallets/ajuna-nft-staking/src/lib.rs
- pallets/ajuna-nft-staking/src/tests/mock.rs
- runtime/solo/src/lib.rs
> Bump MaxFeeClauses

- pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/mod.rs
- pallets/ajuna-awesome-avatars/src/types/season.rs
> #270 Handle overflow

- pallets/ajuna-awesome-avatars/src/types/avatar/force.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/nft.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/tools/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/tools/v1.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/avatar_utils.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/assemble.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/build.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/equip.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/glimmer.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/spark.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/mutator.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/test_utils.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/types.rs
Changes:
- move the `ByteConvertible` and `Ranged` traits up to the avatar level
- (re)move `ForceType` into the upper level `Force`
> [PLAT-795] Consolidate Force types

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v1.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/avatar_utils.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/test_utils.rs
Refactoring forge.
There will be some more refactors after [PLAT-746](https://ajunanetwork.atlassian.net/browse/PLAT-746) and [PLAT-759](https://ajunanetwork.atlassian.net/browse/PLAT-759).
[PLAT-746]: https://ajunanetwork.atlassian.net/browse/PLAT-746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PLAT-759]: https://ajunanetwork.atlassian.net/browse/PLAT-759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PLAT-797] First cut of refactoring forge

- pallets/ajuna-awesome-avatars/src/migration/v5.rs
- runtime/bajun/src/lib.rs
> [PLAT-794] Migration for Avatar V2

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types/season.rs
I think `u32` is enough for `TradeFilter`.
I'll add more tests later on.
> Review refactor

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/avatar_utils.rs
> fixed std_bug

- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/migration/v5.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types/season.rs
Bringing in the changes from https://github.com/ajuna-network/Ajuna/pull/285, which got dropped when rebasing the other PR.
> [PLAT-801] Followup with migration

- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/avatar_utils.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/build.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/glimmer.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/mate.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/stack.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/tinker.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mutator.rs
This PR contains fixes for some issues found during Season 2 testing among others:
* Fixed glimmer quantity on minting
* Fixed DNA initialization to not be randomized
> Season 2 bug fixes

- pallets/ajuna-awesome-avatars/src/types/season.rs
Similarly to the first 3 bytes (except these are matched per nibble), the 4th quantity byte is matched with `0` as wildcard.
> Filter trade quantity with 0 wildcard

- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/breed.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/equip.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/flask.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/mate.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/spark.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/stack.rs
* Adds additional tests for most forge types
* Fixes issues with stack not calculating correctly dust remains
> Season 2 - Additonal test + Stack fixes

- pallets/ajuna-awesome-avatars/src/migration/v5.rs
> [PLAT-804] Migration for seasonal fees

- resources/bajun/kusama.json
- resources/bajun/rococo/rococo.json
There have been changes in the bootnode configuration of [the chain specs](https://github.com/paritytech/polkadot/tree/master/node/service/chain-specs). This PR brings those changes.
> Update relay chain specs with more bootnodes

- Cargo.lock
- pallets/ajuna-awesome-avatars/Cargo.toml
- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/avatar_utils.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/types.rs
Adds more statistics tests and additional Stack tests
> Season 2 - Statistics tests

- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs
* Adds additional condition to determine_forge_type for ForgeType::Build
> Season 2 - ForgeBuild condition adjustment

- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/avatar_utils.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/mate.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/statue.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/constants.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mutator.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/test_utils.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/types.rs
* Adds the new `ForgeType::Statue`
* Adds supporting logic for the new forge type
* Small refactors here and there
> Season 2 - Statue forge type

- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/constants.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mutator.rs
> updated constants and test

- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/avatar_utils.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/breed.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/glimmer.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/mate.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mutator.rs
This PR adds the features/refactors mentioned in:
* https://ajunanetwork.atlassian.net/browse/ABO-54
* https://ajunanetwork.atlassian.net/browse/ABO-55
> Season 2 - ABO-54 & ABO-55

- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/avatar_utils.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/build.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/flask.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/glimmer.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/stack.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/tinker.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/constants.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mutator.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/test_utils.rs
Adjusts the SP ratio of different material types, additionally adds logic to some Forge types.
> Season 2 - Material Soul ratios + algorithm adjustments

- pallets/ajuna-awesome-avatars/src/migration/v5.rs
- runtime/solo/src/lib.rs
Implements the requirements described in:
* https://ajunanetwork.atlassian.net/browse/ABO-63
* https://ajunanetwork.atlassian.net/browse/ABO-65
> [ABO-63][ABO-65] Fix missing migration + solo runtime migration hook

- pallets/ajuna-awesome-avatars/src/types/avatar/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/avatar_utils.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/assemble.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/breed.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/build.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/equip.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/feed.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/flask.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/glimmer.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/mate.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/spark.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/stack.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/statue.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/tinker.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mutator.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/slot_roller.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/test_utils.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/types.rs
See https://ajunanetwork.atlassian.net/browse/PLAT-813 for details.
> [PLAT-813] Add WrappedAvatar refactors

- pallets/ajuna-awesome-avatars/src/types/season.rs
This PR solves the issue described in https://ajunanetwork.atlassian.net/browse/ABO-67
> [AB0-67] Adjust quantity trade filters

- pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/mod.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v1.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs
Fixes issue described in https://ajunanetwork.atlassian.net/browse/ABO-66
> [ABO-66] Forge over-capacity checks

- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/constants.rs
> probability changes

- pallets/ajuna-awesome-avatars/src/lib.rs
See for details: https://ajunanetwork.atlassian.net/browse/ABO-89
> [ABO-89] TRadeFilters should not apply for Season1 

- pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
- pallets/ajuna-awesome-avatars/src/lib.rs
- pallets/ajuna-awesome-avatars/src/tests.rs
See https://ajunanetwork.atlassian.net/browse/ABO-104 for details.
> [ABO-140] Upgrade storage for someone else and/or for a different season

- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/glimmer.rs
- pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/constants.rs
> fixed constants, gamble bug and added the glimmer burn

- pallets/ajuna-awesome-avatars/src/types/avatar/nft.rs
See https://ajunanetwork.atlassian.net/browse/ABO-138 for details.
> [ABO-138] Add season_id as Avatar NFT attribute

- pallets/ajuna-nft-staking/src/lib.rs
- pallets/ajuna-nft-staking/src/tests/ext/remove.rs
See issue: https://ajunanetwork.atlassian.net/browse/ABO-162
> [Staking] Bugfix - Refunding rewards on contract remove

- Cargo.lock
- Cargo.toml
- runtime/ajuna/src/lib.rs
- runtime/bajun/src/lib.rs
- rust-toolchain.toml
>  Release/0.1.23

- Cargo.lock
- Cargo.toml
- node/cli/src/para/command.rs
- node/service/Cargo.toml
- node/service/src/para.rs
- runtime/ajuna/Cargo.toml
- runtime/ajuna/src/lib.rs
- runtime/bajun/Cargo.toml
- runtime/bajun/src/lib.rs
- runtime/solo/Cargo.toml
- runtime/solo/src/consts.rs
- runtime/solo/src/lib.rs
This PR adds async-backing capabilites to both `bajun` and `ajuna` runtimes. Following the details in this [Guide](https://docs.google.com/document/d/1WQijD3bZTCsudOyPcDvugv659nCa2hEp2b_8eRU0h-Q/edit?usp=sharing)
> [runtime] Add async-backing support

- Cargo.toml
- runtime/ajuna/src/lib.rs
- runtime/bajun/src/lib.rs
>  Release/0.1.25

- runtime/solo/src/lib.rs
Increases the limits for solo runtime `pallet_ajuna_nft_staking`
> [Staking] Increase limits
