pallets/ajuna-board/src/lib.rs
pallets/ajuna-board/src/tests.rs

Introduces arbitrary identifiers for boards so that they can be easily referenced outside of L2.

Use arbitrary identifier for board

---

pallets/ajuna-gameregistry/src/lib.rs
pallets/ajuna-gameregistry/src/tests.rs

In order for a player to know the game they are in we store a map of the player against the game id created

Track game id for player

---

Cargo.lock
node/cli/Cargo.toml
node/cli/src/command_helper.rs
runtime/solo/src/lib.rs

Adding back `CheckNonZeroSender` and `pallet-asset-tx-payment` as part of [PLAT-276](https://ajunanetwork.atlassian.net/browse/PLAT-276).
The changes are essentially reverting these two commits:
- https://github.com/ajuna-network/Ajuna/pull/15/commits/85869dc99e12165e618bb66bc176a8aa74597ff9
- https://github.com/ajuna-network/Ajuna/pull/15/commits/2f7b8fe805ead4cb4cfa14f0fb2a38ee15c69bbc

[PLAT-276] Reinstate CheckNonZeroSender and asset payment for SignedExtra

---

ajuna-common/src/lib.rs
pallets/ajuna-board/src/dot4gravity.rs
pallets/ajuna-board/src/guessing.rs
pallets/ajuna-board/src/lib.rs
pallets/ajuna-board/src/mock.rs
pallets/ajuna-board/src/tests.rs

This PR aims to tackle the problem described in https://ajunanetwork.atlassian.net/browse/PLAT-349 in order to do the following changes have been implemented:
* Added `on_idle` hook to the `pallet_ajuna_board` Pallet which checks periodically for stale Games to clean
* Added the `get_next_player` method to the `TurnBasedGame` trait
* Added the `abort` method to the `TurnBasedGame` trait

[PLAT-349] Timeout of a Game

---

node/cli/src/cli.rs

Realised a silly mistake of not enabling for `ajuna` :sweat_smile:

Add missing `ajuna` feature for cli

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs

See https://ajunanetwork.atlassian.net/browse/PLAT-392 for details, in short:
* Adds Organizer storage to track season organizer account
* Adds extrinsics to set the Organizer and verify that a given Account is the current organizer

[PLAT-392] AAA pallet - Organizer storage and logic

---

.github/pull_request_template.md
.github/workflows/check-pull-request.yml
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs

[Some lints weren't caught in `main`](https://github.com/ajuna-network/Ajuna/runs/7985231256?check_suite_focus=true) due to `clippy` not running for all targets on PR branches.
Changes:
- make clippy, check and test to run for all targets by default
- update PR template accordingly
- add `ExtBuilder` to allow populating some storage items to avoid reptition

Fix CI with tidyups

---

ajuna-common/src/lib.rs
pallets/ajuna-board/src/dot4gravity.rs
pallets/ajuna-board/src/guessing.rs

As identified by @andyjsbell, a player can win by not playing. The fix is to make the last player winner (instead of next player).
Changes:
- add and implement `get_last_player` method on `TurnBasedGame` trait

[PLAT-382] Make last player winner on idle

---

pallets/ajuna-board/README.md
pallets/ajuna-board/src/lib.rs
pallets/ajuna-board/src/mock.rs
pallets/ajuna-board/src/tests.rs
runtime/solo/src/lib.rs

In order to dispute a stale board any signing transaction can be used to challenge the stale board.  If the board is stale then the game is awarded to the next player to play.

[PLAT-416] implement xt

---

pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types.rs

`Season` instantiation was getting too verbose so abstracting some of it away.

Abstract test boilerplates

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types.rs

Combining `SeasonMetadata` into `Season` as I don't see any benefit from the normalisation.

Consolidate SeasonMetadata into Season

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types.rs

Removing `Hooks` based on offline discussion. Trade-off is that the `mint` and `forge` extrinsics will have small overhead of (de)activating active season.
Changes:
- combine `new_season` and `update_season` into `upsert_season`
- remove Hooks impl block
- add lazy `toggle_season()` on every mint
- remove duplicated tests for minting
- rename `rarity_tiers` -> `rarity_tiers_single_mint`

Refactor Hooks

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types.rs

Based on offline discussion with @darkfriend77, we don't need to scale soul points based on rarity and variation.

Refactor into non-scaling soul points

---

pallets/battle-mogs/src/lib.rs
pallets/battle-mogs/src/mock.rs
pallets/battle-mogs/src/tests.rs
pallets/battle-mogs/src/types.rs

See https://ajunanetwork.atlassian.net/browse/BAT-367 for details. In short: 
* Refactored pallet code to not need the indexed storages previously defined.

[BAT-367] Refactor MogwaiStruct Storage to BoundedVec

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types.rs

We got the rare avatar minting requirements wrong:
- Rare avatars should only be obtainable through forging (in an upcoming PR)
- An avatar is considered rare when all of its components are of the highest tier
Also the highest tier shouldn't be mint-able so the current mint prob implementation needs refactoring.
Changes:
- removed rare avatar logic (will be re-implemented in a follow up PR in regards to forging)
- refactored `Season` struct
- moved a few `ensure!`s as methods
- removed soul points calculation logic because we just want to get a random number between 1 and 100
- (so a low tier avatar can have amazing soul points and vice versa)

Remove rare avatar minting with refactored mint probability

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types.rs

Moving a couple of constants into `GlobalConfigs` storage so the organizer can update them without runtime upgrade.

Move constants into storage

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types.rs

Season tiers were sorted in descending order so all minted avatars were of the higher tier.
Changes:
- make tiers sorted in ascending order (probabilities are sorted in descending)
- make all extrinsics available by default
- change `RarityPercent` -> u16 to avoid it being rendered as byte array from Polkadot UI

Fix tier ordering

---

pallets/battle-mogs/src/lib.rs
pallets/battle-mogs/src/mock.rs
pallets/battle-mogs/src/tests.rs

See https://ajunanetwork.atlassian.net/browse/BAT-385 for details. In short:
* Added additional checks to restrict actions performable on a mogwai on sale
* Added new error variant to reflect invalid state for a mogwai on sale

[BAT-385] Ensure no actions, when price set

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types.rs

Re: [AAATAR-300](https://ajunanetwork.atlassian.net/browse/AAATAR-300)
Changes:
- move `OutOfSeason` check into `fn toggle_season`
- allow `toggle_season` to bypass `OutOfSeason` check when a season is deactivated
- abstract active season check into a season method
- some tidy up refactors

[AAATAR-300] Fix season update

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types.rs

Re: [AAATAR-303](https://ajunanetwork.atlassian.net/browse/AAATAR-303)
Changes:
- added `SeasonMaxTierForges` storage to keep track of seasonal highest tier forges
- added `IsSeasonPrematurelyEnded` storage which gets updated when `max_tier_forges` has reached

[AAATAR-303] Premature season ending

---

pallets/battle-mogs/src/lib.rs
pallets/battle-mogs/src/mock.rs
pallets/battle-mogs/src/tests.rs

See https://ajunanetwork.atlassian.net/browse/BAT-357 for details. In short:
* `BattleMogs::sacrifice`: Added balance check which limits the amount of currency the account that sacrificed the mogwai receives from it, so that it never exceeds the maximum balance.
* `BattleMogs::sacrifice_into`: Replace simple `AddAssign` with `saturating_add` to avoid overflowing when adding mogwai intrinsics.
* `BattleMogs::morph_mogwai`: Updated `tip_mogwai` to use `saturating_add` insead of `AddAssign`
* `BattleMogs::breed_mogwai`: Updated `tip_mogwai` to use `saturating_add` insead of `AddAssign`

[BAT-357] Overflow tests on the intrinsics and balance changes

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types.rs

Re: [AAATAR-305](https://ajunanetwork.atlassian.net/browse/AAATAR-305)
Changes:
- consolidate all boolean `StorageValue` into `CurrentSeasonStatus`
- remove obsolete balance checks (since extrinsics are atomic now)
- also bubble up pallet_balance errors
- fix a mistake in season ending logic
- add `SeasonStatus.early` to handle early season access

[AAATAR-305] Early season access

---

pallets/ajuna-awesome-avatars/src/benchmarking.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/account.rs

Changes:
- refactor `AccountInfo.stats` with categorised nesting
- remove `LastMintedBlockNumbers` and add `PlayStats.last` as replacement

Enrich `AccountInfo` with last minted block number

---

.github/workflows/release.yml

Changes:
- add `outputs.image_tag` to propagate image tag other jobs
- add `release-onf` job that:
- runs after `docker-release`
- and updates network specs on OnF to reference the newly published images
TODO:

[PLAT-627] Add a job to release on OnF

---

node/cli/src/benchmarking.rs
node/cli/src/cli.rs
node/cli/src/command.rs
node/service/src/solo.rs
pallets/ajuna-board/src/lib.rs
pallets/ajuna-board/src/tests.rs
rpc/src/lib.rs
runtime/ajuna/src/lib.rs
runtime/bajun/src/lib.rs
runtime/solo/src/lib.rs
runtime/solo/src/types.rs

See https://ajunanetwork.atlassian.net/browse/PLAT-434 for details. In short:
* Moved seed generation to just after a game is initialized instead of when a winner is declared.

[PLAT-434] Seeds are generated post winning condition only

---

.github/workflows/check-pull-request.yml
.github/workflows/release.yml

It's noted from the [latest release](https://github.com/ajuna-network/Ajuna/actions/runs/3466579147) that the following actions are outdated:
- [actions-rs/cargo@v1](https://github.com/actions-rs/cargo)
- we don't need this action anyway because GitHub runners come with `cargo` pre-installed

Remove outdated actions

---

.github/workflows/check-pull-request.yml

Reverting https://github.com/ajuna-network/Ajuna/pull/38/commits/e0332f276f5070b415cc9f13ab38e34823653281 as the resource exhaustion error doesn't seem to happen anymore.
The `Test` job now takes ~30 min, compared to more than 1 hr before.

Use all available CPUs for running tests

---

.github/workflows/check-pull-request.yml

Fixing [this issue](https://github.com/ajuna-network/Ajuna/actions/runs/3905990960/jobs/6674478626) by removing the `notify` job.
We'll subscribe for changes via the official Github Slack integration.

ci: remove slack notify

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/season.rs

Forging should be allowed regardless of the status of a season. It can only be switched off by updating the global config.

[PLAT-682] Forging is uninterrupted

---

pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/avatar.rs

Soul points were increased only when avatars could potentially be forged into a higher tier. Fixing this so that they accumulate regardless of the outcome of forging.

[PLAT-686] Accumulate soul points regardless of outcome

---

node/service/src/chain_spec/bajun.rs
node/service/src/chain_spec/solo.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/mock.rs

The default values are not populated in the storage items. Instead, they are fetched when the storage is empty to require SDKs to handle fallback.
Moving the default values to `genesis_build` so the corresponding storage items are populated at genesis.

Move default values in genesis build

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/tests.rs

Seasonal `max_tier_avatars` should increment only (as a way of triggering premature end).

Revert max avatar decrement

---

pallets/ajuna-awesome-avatars/src/types/avatar.rs

Adding a test for comparing avatars' DNA.

Add a test for compare

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/tests.rs

Implements whitelisting of accounts whose free mint balance is at least 1.

[PLAT-694] Implement whitelisting

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/tests.rs

Allows free mint for all players at premature season ending.

[PLAT-695] Allow free mints at premature ending

---

.github/scripts/free_disk_space.sh
.github/workflows/check-pull-request.yml

Remove stuff we don't use to free up space.

[PLAT-741] Remove needless packages and tools

---

pallets/ajuna-awesome-avatars/src/benchmarking.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/avatar/nft.rs

Removing these two redundant calls:
- `issue_free_mints`
- `withdraw_free_mints`

[PLAT-754] Remove unused free mint calls

---

.github/workflows/check-pull-request.yml

Use cache for each matrix

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/tests.rs

Trade fee was deposited into the current season's treasury, instead of the traded avatar's season (re: [PLAT-760](https://ajunanetwork.atlassian.net/browse/PLAT-760)).
[PLAT-760]: https://ajunanetwork.atlassian.net/browse/PLAT-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PLAT-760] Fix treasury season ID of trade fees

---

node/service/src/chain_spec/bajun.rs
node/service/src/chain_spec/solo.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-nft-transfer/src/benchmarking.rs
pallets/ajuna-nft-transfer/src/lib.rs
pallets/ajuna-nft-transfer/src/mock.rs
pallets/ajuna-nft-transfer/src/tests.rs
pallets/ajuna-nft-transfer/src/traits.rs
runtime/bajun/src/lib.rs
runtime/solo/src/lib.rs

I think it's nicer for users to be able to view their NFTs under the "My NFTs" page ([see Westmint example](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestmint-rpc.polkadot.io#/nfts/my-nfts)). We can also expect users to pay `ItemDeposit` when freeing an avatar.
The PR removes `holding_account_id` and uses `owner` instead.

Remove transfer holding account

---

pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-nft-staking/src/benchmarking.rs
pallets/ajuna-nft-staking/src/lib.rs
pallets/ajuna-nft-staking/src/tests.rs
pallets/ajuna-nft-transfer/src/lib.rs
pallets/ajuna-nft-transfer/src/tests.rs

Trivially removing storage getters since they will be deprecated in upcoming releases (RE: substrate: 13365).

Remove storage getters

---

pallets/ajuna-nft-staking/src/contracts.rs
pallets/ajuna-nft-staking/src/lib.rs
pallets/ajuna-nft-staking/src/mock.rs
pallets/ajuna-nft-staking/src/tests.rs

Adding the additional extrinsic calls:
- `remove`: opposite of `create`, where a creator can remove existing available (not accepted yet) contracts
- `cancel`: opposite of `accept`, where stakers can cancel ongoing contracts for a fee
- `snipe`: similar to `claim`, where other players can claim expired, fulfilled contracts

[PLAT-786] Additional NFT-staking extrinsics

---

pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/account.rs
pallets/ajuna-awesome-avatars/src/types/avatar/force.rs
pallets/ajuna-awesome-avatars/src/types/avatar/mod.rs
pallets/ajuna-awesome-avatars/src/types/avatar/rarity_tier.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/mod.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v1.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/avatar_utils.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/assemble.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/breed.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/build.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/equip.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/feed.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/glimmer.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/mate.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/mod.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/spark.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/stack.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/combinator/tinker.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/constants.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/mod.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/mutator.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/slot_roller.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/test_utils.rs
pallets/ajuna-awesome-avatars/src/types/avatar/tools/v2/types.rs
pallets/ajuna-awesome-avatars/src/types/config.rs
pallets/ajuna-awesome-avatars/src/types/season.rs

Since we want to have more complex avatar logic and types in the future, this PR plays around with the idea of trying to 
isolate parts of the logic behind avatar version enum.

Avatar V2 prototype

---

pallets/ajuna-awesome-avatars/Cargo.toml
pallets/ajuna-awesome-avatars/benchmarking/Cargo.toml
pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/migration/v5.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v1.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs

Changing the `Owners` storage from `Map` -> `DoubleMap` with `SeasonId` as the second key.
There will be another PR for updating the `Trade` storage.

[PLAT-746] Seasonal inventory

---

pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/migration/v5.rs
pallets/ajuna-awesome-avatars/src/tests.rs

Changing the Trade storage from Map -> DoubleMap with SeasonId as the first key.

[PLAT-759] Seasonal trade storage

---

pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/season.rs

See for details: https://ajunanetwork.atlassian.net/browse/PLAT-801 
In short: Adds the capability to limit which kind of avatars can be traded at the Season level.

[PLAT-801] Season 2: Trade filters

---

.cargo/config.toml
.github/workflows/release.yml
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/avatar_utils.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/breed.rs
rust-toolchain.toml

Fix CI for release

---

pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/avatar_utils.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs

Refactoring determine forge type

---

pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/migration/v5.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/avatar/mod.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v1.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/avatar_utils.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/test_utils.rs
pallets/ajuna-awesome-avatars/src/types/config.rs
pallets/ajuna-awesome-avatars/src/types/season.rs

This PR splits the `AvatarVersion` enum into two separate enums with new meanings:
* `DnaEncoding` represents how the bytes in the Avatar's DNA are encoded and what each byte represents.
* `LogicGeneration` represents which of the available Mint/Forge logics is used
Each `LogicGeneration` produces avatars with a given `DnaEncoding`, but a given `DnaEncoding` version could be produced/manipulated by different `LogicGeneration` generations.

[PLAT-803] Split AvatarVersion

---

node/cli/src/para/command.rs
pallets/ajuna-awesome-avatars/src/migration/v5.rs

fix(cli): remove if for try runtime

---

pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/tests.rs

Changes season_id reference point to be the leader avatar in the forge instead of the current season.

Season 2 - Fix forging out of season

---

pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/weights.rs

Removes `fix_variation` extrinsic and all its references.

[ABO-64] Remove fix_variation extrinsic

---

pallets/ajuna-awesome-avatars/src/types/avatar/rarity_tier.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/avatar_utils.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/assemble.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/equip.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/feed.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/mate.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/constants.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs

* Adds moon clock logic for `ForgeType::Mate`
* Restricts to maximum of 2 Toolbox uses per Assembly run
* Adds additional logic to `ForgeType::Feed`

Season 2 - Additional logic/adjustments

---

pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/avatar_utils.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs

fixed missing on eggs and fixed naming

---

pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/build.rs

See for details: https://ajunanetwork.atlassian.net/browse/ABO-90

[ABO-90] Blueprint building should not increase SP

---

pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/tests.rs

Adds an additional check the the `transfer_free_mints` extrinsic. This check blocks accounts that have neither minted nor forged anything from transferring their free mints.

[Season 2] Add account activity check for free mint transfer

---

pallets/ajuna-nft-staking/benchmarking/src/lib.rs
pallets/ajuna-nft-staking/src/contracts.rs
pallets/ajuna-nft-staking/src/tests/ext/accept.rs
pallets/ajuna-nft-staking/src/tests/ext/cancel.rs
pallets/ajuna-nft-staking/src/tests/ext/claim.rs
pallets/ajuna-nft-staking/src/tests/ext/create.rs
pallets/ajuna-nft-staking/src/tests/ext/snipe.rs
pallets/ajuna-nft-staking/src/tests/mock.rs

This PR adds limited AttributeNamespace support similar to what https://github.com/paritytech/substrate/blob/polkadot-v0.9.42/frame/nfts/src/types.rs#L326 accomplishes.

[NFT-Staking] Attribute namespace support

---

pallets/ajuna-nft-staking/benchmarking/src/lib.rs
pallets/ajuna-nft-staking/benchmarking/src/mock.rs
pallets/ajuna-nft-staking/src/contracts.rs
pallets/ajuna-nft-staking/src/lib.rs
pallets/ajuna-nft-staking/src/tests/ext/accept.rs
pallets/ajuna-nft-staking/src/tests/ext/cancel.rs
pallets/ajuna-nft-staking/src/tests/ext/claim.rs
pallets/ajuna-nft-staking/src/tests/ext/create.rs
pallets/ajuna-nft-staking/src/tests/ext/snipe.rs
pallets/ajuna-nft-staking/src/tests/mock.rs
runtime/solo/src/lib.rs

This PR adds the following features to the `nft-staking` pallet:
* Adds `target_index` to the `ContractClause` struct
* Adds `nft_staking_amount` and `nft_fee_amount` to the `Contract` struct
* Adds checks for both stake and fee NFTs to check the amount of unique values in the extrinsic call of `accept`
* Adds `ContractsMetadata` storage, used to pair each contract with a string bytes of metadata.

[Staking] Pallet enhancements

---

pallets/ajuna-nft-staking/benchmarking/src/lib.rs
pallets/ajuna-nft-staking/benchmarking/src/mock.rs
pallets/ajuna-nft-staking/src/contracts.rs
pallets/ajuna-nft-staking/src/lib.rs
pallets/ajuna-nft-staking/src/tests/ext/accept.rs
pallets/ajuna-nft-staking/src/tests/ext/cancel.rs
pallets/ajuna-nft-staking/src/tests/ext/claim.rs
pallets/ajuna-nft-staking/src/tests/ext/create.rs
pallets/ajuna-nft-staking/src/tests/ext/snipe.rs
pallets/ajuna-nft-staking/src/tests/mock.rs
runtime/solo/src/lib.rs

This pallet replaces both NFT attribute key and value for `BoundedVec` with configurable bound limits, like `pallet-nfts`.

[Staking] Match NFT attribute key/value to pallet-nfts spec

---

pallets/ajuna-awesome-avatars/benchmarking/src/lib.rs
pallets/ajuna-awesome-avatars/benchmarking/src/mock.rs
pallets/ajuna-awesome-avatars/src/lib.rs
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/avatar/nft.rs
pallets/ajuna-nft-staking/benchmarking/src/mock.rs
pallets/ajuna-nft-staking/src/tests/mock.rs
pallets/ajuna-nft-transfer/src/lib.rs
pallets/ajuna-nft-transfer/src/mock.rs
pallets/ajuna-nft-transfer/src/tests.rs
pallets/ajuna-nft-transfer/src/traits.rs
runtime/bajun/src/lib.rs
runtime/solo/src/lib.rs

This PR aims at changing the typing of the NFT attribute in the `NFTConvertible` interface exposed in the `pallet-ajuna-nft-transfer`. Many supporting changes have been applied in order for it to work as expected.

[Staking] Adjusting types of Avatar attributes on NFT conversion

---

pallets/ajuna-nft-staking/src/lib.rs
pallets/ajuna-nft-staking/src/tests/ext/claim.rs
pallets/ajuna-nft-staking/src/tests/ext/create.rs
pallets/ajuna-nft-staking/src/tests/ext/remove.rs
pallets/ajuna-nft-transfer/src/lib.rs
pallets/ajuna-nft-transfer/src/tests.rs

This PR addresses the issues in the following tickets:
* https://ajunanetwork.atlassian.net/browse/ABO-148
* https://ajunanetwork.atlassian.net/browse/ABO-149
* https://ajunanetwork.atlassian.net/browse/ABO-150
* https://ajunanetwork.atlassian.net/browse/ABO-151

Bugs and missing checks ensure_acceptable and transfer is locked

---

pallets/ajuna-nft-staking/src/lib.rs
pallets/ajuna-nft-staking/src/tests/ext/cancel.rs
pallets/ajuna-nft-staking/src/tests/ext/claim.rs
pallets/ajuna-nft-staking/src/tests/ext/remove.rs
pallets/ajuna-nft-staking/src/tests/ext/snipe.rs

This PR tackles the issues mentioned in the following Jira tickets:
* https://ajunanetwork.atlassian.net/browse/ABO-152
* https://ajunanetwork.atlassian.net/browse/ABO-152
* https://ajunanetwork.atlassian.net/browse/ABO-155
* https://ajunanetwork.atlassian.net/browse/ABO-156

[Staking] Fixes and logic adjustments

---

pallets/ajuna-nft-staking/benchmarking/src/lib.rs
pallets/ajuna-nft-staking/src/contracts.rs
pallets/ajuna-nft-staking/src/lib.rs
pallets/ajuna-nft-staking/src/tests/ext/accept.rs
pallets/ajuna-nft-staking/src/tests/ext/cancel.rs
pallets/ajuna-nft-staking/src/tests/ext/claim.rs
pallets/ajuna-nft-staking/src/tests/ext/create.rs
pallets/ajuna-nft-staking/src/tests/ext/snipe.rs
pallets/ajuna-nft-staking/src/tests/mock.rs

This PR adds the features mentioned here:
* https://ajunanetwork.atlassian.net/browse/ABO-154
* https://ajunanetwork.atlassian.net/browse/ABO-158

[Staking] Multi rewards and statistics

---

pallets/ajuna-awesome-avatars/Cargo.toml
pallets/ajuna-awesome-avatars/src/mock.rs
pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/avatar/nft.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs

See https://ajunanetwork.atlassian.net/browse/ABO-159 for details.

[NFT-Transfer] Modified avatar encoding

---

pallets/ajuna-awesome-avatars/src/tests.rs
pallets/ajuna-awesome-avatars/src/types/avatar/nft.rs

fixed endocindg of enum uppercase and rarity s1

---

pallets/ajuna-nft-staking/benchmarking/src/lib.rs
pallets/ajuna-nft-staking/src/lib.rs
pallets/ajuna-nft-staking/src/tests/ext/create.rs
pallets/ajuna-nft-staking/src/tests/mock.rs

This PR tackles the issues mentioned in:
* https://ajunanetwork.atlassian.net/browse/ABO-163
* https://ajunanetwork.atlassian.net/browse/ABO-165
* https://ajunanetwork.atlassian.net/browse/ABO-166

[Staking] Contract attributes and sniper check

---

pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/equip.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/combinator/mate.rs
pallets/ajuna-awesome-avatars/src/types/avatar/versions/v2/mod.rs

This PR applies the changes mentioned in the following JIRA tickets:
* https://ajunanetwork.atlassian.net/browse/ABO-144
* https://ajunanetwork.atlassian.net/browse/ABO-145

[Season 2][ABO-144 | ABO-145] Logic adjustments

---

runtime/ajuna/Cargo.toml
runtime/bajun/Cargo.toml
runtime/solo/Cargo.toml

Adds the `experimental` feature to the runtime's default features

Added default 'experimental' feature to runtimes

---

.github/workflows/release.yml
.maintain/zombienet-config.toml
.maintain/zombienet-tests.zndsl
node/cli/src/para/command.rs
node/service/src/chain_spec/ajuna.rs
node/service/src/chain_spec/bajun.rs
pallets/ajuna-awesome-avatars/src/migration/v5.rs
runtime/ajuna/src/lib.rs
runtime/bajun/src/lib.rs

This PR has the following changes:
* Fixes in the bajun and ajuna runtimes related to async-backing
* Adds two new jobs to the release check `try-runtime` and `zombienet` checks
* Adds adjustments and files needed for the new checks to work

[Release] Fixes and changes preparing for version 0.1.28

---

runtime/ajuna/src/lib.rs
runtime/bajun/src/lib.rs

Changes the configuration to reach 6s block times through increasing processing velocity instead of reducing block times

[Async-Backing] Adjust block time target

---

node/service/src/chain_spec/ajuna.rs
node/service/src/chain_spec/bajun.rs
node/service/src/chain_spec/mod.rs

Adds the option to specify `bad_blocks` extension to the runtime's chain-spec file.

[ChainSpec] Add `bad_blocks` extension

---

runtime/ajuna/src/lib.rs

This PR adjusts the `BlockNumberProvider` for the Ajuna runtime so that it uses the relay chain block number instead of the parachain block number for the vesting calculations.

[ABO-197] Add orml-vesting to the RelayChain block for Ajuna Network
